### ISSUE TITLE
Roadmap image is too small to read

### ISSUE THREAD

**Issue by justerhan** [interlock-network/interlock-docs#13]
### Bug description

The roadmap image on https://interlock-network.github.io/interlock-whitepaper/#roadmap is too small to read, needs to be displayed in another format: embedded slide, mermaid ? , etc.

### Steps to reproduce

Visit https://interlock-network.github.io/interlock-whitepaper/#roadmap on a 4k monitor and check if images are readable.

### Expected behavior

Images should be readable

**Comment by Treevuhh** [comment]
I created a larger size ratio graphic at 3242px by 1888px for the existing roadmap png and it still appears small without zooming in. 
displaying it in another format may be needed. Mermaid might be too bland, embedded slide sounds better imo

**Comment by justerhan** [comment]
The roadmap needs to be moved into Github Projects then linked, I don't think we can (or should) have an image that resolution anyways -- its too large and the ratio of it will almost certainly guarantee it remains unreadable on mobile, if not desktop too.

**Comment by Treevuhh** [comment]
Updated and resized image as well as the Knowledge Base entry [here](https://github.com/interlock-network/knowledgebase-public/blob/main/what/roadmap.md)
