### ISSUE TITLE
Whitepaper Needs to Clarify What is Aspirational and what is Possible Near-Term

### ISSUE THREAD

**Issue by galactic-beyond** [interlock-network/interlock-docs#3]
It's possible that we have outgrown our own whitepaper (wouldn't be the first time).

Anything that is ambiguous or unclear in the whitepaper, needs to be made clear.

I have been staring at it for so long that, it is unclear to me what would be unclear to an outsider.

So, maybe it needs some major brain-surgery. Or maybe it needs a complete rewrite.

Either way, it needs to be more accessible and clearer. We wouldn't want users to misunderstand what we are doing and how we are doing it. It might come off as deceptive, and we want to earn people's trust.

Whoever ends up doing this, feel free to do whatever you think is necessary -- I'll be focusing on other more pressing problems, in code-land.

**Comment by Treevuhh** [comment]
Has been handed over to Andrew.  Coming Sep. 2023
